itda-ieoso/itda-ieoso_frontend

src/App.jsx
src/component/page/class/Create.jsx
src/component/page/class/Setting.jsx

---
- closed: #24 
---
- Setting.jsx UI 구현
- Create.jsx 수정
- 
---
(관련 이미지 첨부)  
Setting.jsx 구현
Create.jsx 수정
- 필수 입력 필드 * 추가
- 수업 난이도 부분 스타일 변경
---

feat: 강의실 설정 페이지 UI 구현

---

src/App.jsx
src/component/api/api.js
src/component/api/usersApi.js
src/component/contexts/usersContext.jsx
src/component/img/icon/usericon.svg
src/component/page/Class.jsx
src/component/page/Dashboard.jsx
src/component/page/LogIn.jsx
src/component/page/MainPage.jsx
src/component/page/Participate.jsx
src/component/page/SignUp.jsx
src/component/page/users/LogIn.jsx
src/component/page/users/SignUp.jsx
src/component/page/users/UsersInfoContainer.jsx
src/component/ui/TopBar.jsx
src/component/ui/class/EditClass.jsx
src/style/Styles.jsx

---
- #21 
---
- Context API로 로그인 상태, 유저 정보 전역으로 관리
- 로그인 후 헤더로 토큰 받게 수정
- 로그인 상태에 따라서 헤더 출력 다르게 수정
---
(관련 이미지 첨부)  
https://github.com/user-attachments/assets/5275dc4f-ee11-4935-8b33-dc6bae620944
---

feat: 로그인, 회원가입, 이메일 중복 확인, 로그아웃, 유저 정보 api 연동

---

src/component/page/users/SignUp.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

feat: 약관 동의 내용 회원가입 API에 추가

---

src/component/page/class/Create.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

feat: 강의실 초기 생성 api 연결

---

src/component/page/class/Curriculum.jsx
src/component/page/class/CurriculumEdit.jsx
src/component/page/class/Students.jsx
src/component/page/class/Summary.jsx
src/component/ui/class/AdminTopBar.jsx
src/component/ui/class/CurriculumSidebar.jsx
src/component/ui/curriculum/CurriculumSection.jsx
src/component/ui/curriculum/EditContainer.jsx
src/component/ui/curriculum/EditableSection.jsx

---
- closed: #36 
---
- 강의실 커리큘럼 편집 페이지 ui 수정
- 
---
(관련 이미지 첨부)  
---
아직 api 연동은 안된 상태입니다

feat: 강의실 커리큘럼 편집 페이지 ui 수정

---

src/component/page/class/Create.jsx
src/component/ui/CustomTimePicker.jsx

---
---
- 
- 
---
https://github.com/user-attachments/assets/6c5a242c-1656-4d1d-843e-1176d41b10cb
미세한 조정은 어려워서, 위아래 클릭 시 이동할 수 있는 기능도 구현해두었습니다!

feat: CustomTimePicker 구현

---

package-lock.json
package.json
src/component/page/class/Playing.jsx
src/component/ui/class/PlayingCurriculumSidebar.jsx
src/component/ui/class/VideoPlaying.jsx

---
- closed: #48
---
- 유튜브 API 사용해 API 연결 완료
- 커리큘럼 사이드바 분리
---
(관련 이미지 첨부)  
---

Feat: 강의실 수강 화면 API 연동

---

src/component/page/class/AssignmentSubmit.jsx
src/component/page/class/Create.jsx
src/component/page/class/Curriculum.jsx
src/component/page/class/Setting.jsx
src/component/ui/CustomTimePicker.jsx
src/component/ui/DragZone.jsx
src/component/ui/Modal.jsx
src/component/ui/class/AssignmentModal.jsx
src/component/ui/class/EntryCodeModal.jsx

---
- closed: #42 
---
- 과제 제출 및 수정하기 API 구현
- 모달창 추가
- CustomTimePicker 오류 수정
---
(관련 이미지 첨부)  
---
파일 누르면 다운로드 기능은 구현하다가 실패..
강의실 생성 이후 커리큘럼 페이지 말고 개요 페이지로 이동하도록 구현하는건 다음 PR 에서..

feat: 과제 제출 API 구현

---

src/component/img/icon/videored.svg
src/component/page/Participate.jsx
src/component/page/class/AssignmentSubmit.jsx
src/component/page/class/Create.jsx
src/component/page/class/Playing.jsx
src/component/ui/class/PlayingCurriculumSidebar.jsx
src/component/ui/class/VideoPlaying.jsx

---
- closed: #48 
---
- 커리큘럼 사이드바 구현
- 파일 다운 구현
- 과제 상태에 따른 로직 변경
---
(관련 이미지 첨부)  
---

feat: 커리큘럼 사이드바 구현, 파일 다운로드 구현

---

src/component/img/class/check/late_submission.svg
src/component/page/class/Curriculum.jsx
src/component/page/class/CurriculumEdit.jsx
src/component/page/class/NoticeCreate.jsx
src/component/page/class/StudentDetail.jsx
src/component/ui/class/CurriculumSidebar.jsx
src/component/ui/class/StudentProgressTable.jsx
src/component/ui/curriculum/CurriculumSection.jsx

---
- closed: #58 
---
- 강의실 공지 작성 UI 수정
- 커리큘럼 편집 페이지 UI 수정
---
(관련 이미지 첨부)  
---
아직 완벽한 반응형 아님

FIX: 강의실 공지 작성 화면 및 커리큘럼 편집 페이지 UI 수정

---

src/component/page/class/Curriculum.jsx
src/component/ui/class/CurriculumSidebar.jsx

---
- closed: #58 
---
- 강의 자료 다운 API 연동 완료
- 커리큘럼 사이드바 반응형 디자인
---
(관련 이미지 첨부)  
---

feat: 강의 자료 다운 API 연동 완료

---

index.html
src/component/page/class/Playing.jsx
src/component/ui/class/AssignmentShowBox.jsx
src/component/ui/class/PlayingCurriculumSidebar.jsx

---
---
- 폰트 추가
- 과제 제출 화면 다운로드 fix
- 자료 다운로드 여부 확인 코드 추가
- 강의 수강 화면 상단 > navigation 주소 변경 
---
(관련 이미지 첨부)  
---

FIX: 과제 제출 다운 수정

---

src/component/page/ClassList.jsx
src/component/page/class/AssignmentSubmit.jsx
src/component/page/class/Create.jsx
src/component/page/class/Notice.jsx
src/component/page/class/NoticeCreate.jsx
src/component/page/class/Overview.jsx
src/component/ui/class/ClassSidebar.jsx
src/style/GlobalStyles.jsx

---
- closed: #70 
---
- 강의 개요 UI 수정 (난이도 추가)
- 강의 리스트 UI 수정 (난이도 추가)
- 공지 작성 수정사항 반영
---
(관련 이미지 첨부)  
---

fix: 강의 개요, 강의 리스트, 공지 작성 수정사항 반영

---

src/component/page/class/Curriculum.jsx
src/component/page/class/CurriculumEdit.jsx
src/component/ui/class/CurriculumSidebar.jsx
src/component/ui/curriculum/EditableSection.jsx

---
- closed: #72 
---
- 기간 내 다운로드 및 접근 가능하도록 설정
- 반응형 디자인 (미완)
---
(관련 이미지 첨부)  
---

FEAT: 기간 내 다운로드 및 접근 가능하도록 설정

---

index.html
src/component/page/Class.jsx
src/component/page/ClassList.jsx
src/component/page/class/Setting.jsx
src/component/page/dashboard/Dashboard.jsx
src/component/page/dashboard/Sidebar.jsx
src/component/page/dashboard/TaskList.jsx
src/component/page/dashboard/WeekCalendar.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

Fix/66 대시보드 수정

---

src/component/page/class/Curriculum.jsx
src/component/page/class/CurriculumEdit.jsx
src/component/ui/curriculum/DateTimeEdit.jsx

---
- closed: #72 
---
- 바뀐 커리큘럼 데이터에 맞춰 코드 수정
- 
---
(관련 이미지 첨부)  
---

FIX:  바뀐 커리큘럼 데이터에 맞춰 수정

---

src/component/page/class/Curriculum.jsx
src/component/ui/class/CurriculumSidebar.jsx

---
- closed: #72 
---
- 커리큘럼 사이드 바 넘버링 삭제 
- 커리큘럼 UI 수정
- 
---
(관련 이미지 첨부)  
---

FIX: 커리큘럼 사이드 바 넘버링 삭제 및 UI 수정

---

src/component/page/class/Curriculum.jsx
src/component/page/class/CurriculumEdit.jsx
src/component/ui/curriculum/DateTimeEdit.jsx
src/component/ui/curriculum/EditableSection.jsx

---
- closed: #72 
---
- 섹션 접근 가능 시간 수정 
- 섹션 편집 : 기간 설정 코드 수정
---
(관련 이미지 첨부)  
---

FIX: 섹션 접근 가능 시간 수정 및 기간 설정 코드 수정

---

src/component/page/class/CurriculumEdit.jsx
src/main.jsx

---
- closed: #82 
---
- 커리큘럼 편집 중 순서 변경 버그 해결
- 
---
(관련 이미지 첨부)  
---

FIX: 커리큘럼 편집 중 순서 변경 버그 해결

---

src/component/page/dashboard/Dashboard.jsx
src/component/page/dashboard/Sidebar.jsx
src/component/page/dashboard/TaskList.jsx
src/component/page/dashboard/WeekCalendar.jsx
src/style/GlobalStyles.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

fix: 대시보드 출력 방식 변경

---

src/component/page/Class.jsx
src/component/page/ClassList.jsx
src/component/page/LandingPage.jsx
src/component/page/class/Create.jsx
src/component/page/class/Overview.jsx
src/component/page/dashboard/Sidebar.jsx
src/component/page/dashboard/WeekCalendar.jsx
src/component/page/users/SignUp.jsx
src/component/ui/class/AdminTopBar.jsx
src/component/ui/class/ClassSidebar.jsx
src/component/ui/class/PlayingCurriculumSidebar.jsx
src/style/GlobalStyles.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

design: 디자인 수정

---

src/component/page/class/Create.jsx
src/component/page/class/Setting.jsx
src/component/ui/CustomTimePicker.jsx
src/component/ui/class/AssignmentModal.jsx
src/component/ui/class/EntryCodeCopyModal.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

mod: 강의 설정 및 생성 페이지 스타일 변경

---

src/component/page/class/CurriculumEdit.jsx

---
- closed: #87 
---
- 커리큘럼 편집 시 섹션 하나 이상 유지하도록 강제하는 기능 추가
---
(관련 이미지 첨부)  
---

FEAT: 커리큘럼 편집 시 섹션 하나 이상 유지하도록 강제하는 기능 추가

---

src/component/page/dashboard/Sidebar.jsx
src/component/page/dashboard/WeekCalendar.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

Fix: 대시보드 출력 에러 수정

---

src/component/ui/curriculum/DateTimeEdit.jsx

---
- closed: #92 
---
- 커리큘럼 편집 시 시간 범위 설정 수정
- 
---
(관련 이미지 첨부)  
---

FIX: 커리큘럼 편집 시 시간 범위 설정 수정

---

src/component/page/class/CurriculumEdit.jsx

---
- closed: #94 
---
- 강의 설명 텍스트 클릭 시에도 편집 활성화 유지
- 
---
(관련 이미지 첨부)  
---

FIX: 강의 설명 텍스트 클릭 시에도 편집 활성화 유지

---

src/component/ui/class/AssignmentShowBox.jsx
src/component/ui/class/AssignmentSubmitBox.jsx
src/component/ui/class/PlayingCurriculumSidebar.jsx
src/style/GlobalStyles.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

mod: vh 수정

---

src/component/ui/class/PlayingCurriculumSidebar.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

mod: 과제 기한 재설정

---

src/component/page/dashboard/Sidebar.jsx
src/component/page/dashboard/TaskList.jsx
src/component/page/dashboard/WeekCalendar.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

fix: 늦은 제출일 때도 체크 버튼 표시되게 수정

---

src/component/page/class/Curriculum.jsx

---
---
- 늦은 제출 시에도 커리큘럼 내에서 체크 표시
- 
---
(관련 이미지 첨부)  
---

FEAT: 늦은 제출 시에도 커리큘럼 내에서 체크 표시

---

src/component/page/class/Overview.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

design: 최대 이미지 사이즈 증가

---

src/component/page/class/Curriculum.jsx

---
---
- 커리큘럼 내 영상 체크 버튼 제거
- 
---
(관련 이미지 첨부)  
---

FEAT: 커리큘럼 내 영상 체크 버튼 제거

---

src/component/ui/curriculum/EditableSection.jsx

---
---
- 커리큘럼 편집 시 발생 오류 해결
- 
---
(관련 이미지 첨부)  
---

FIX: 커리큘럼 편집 시 발생 오류 해결

---

src/component/page/class/CurriculumEdit.jsx
src/component/ui/curriculum/DateTimeEdit.jsx
src/component/ui/curriculum/EditableSection.jsx

---
---
- 콘솔 제거
---
(관련 이미지 첨부)  
---

FEAT: 콘솔 제거

---

src/component/page/class/Curriculum.jsx
src/component/ui/class/CurriculumSidebar.jsx

---
---
- 커리큘럼 사이드바에 완료 여부 반영
- 
---
(관련 이미지 첨부)  
---

FEAT: 커리큘럼 사이드바에 완료 여부 반영

---

src/component/page/class/CurriculumEdit.jsx

---
- closed: #106 
---
- 커리큘럼 편집 중 다른 섹션 클릭 시에도 편집 내용 유지
- 
---
(관련 이미지 첨부)  
---

FIX:  커리큘럼 편집 중 다른 섹션 클릭 시에도 편집 내용 유지

---

src/component/api/usersApi.js
src/component/page/users/SignUp.jsx
src/component/ui/TopBar.jsx
src/style/Styles.jsx

---
- closed: #66 
---
- 
- 
---
(관련 이미지 첨부)  
---

fix: 토큰 시간, 헤더 우측 출력 안되게 수정

---

src/component/page/class/CurriculumEdit.jsx
src/component/ui/curriculum/EditableSection.jsx

---
- closed: #118 
---
- 커리큘럼 편집 내 과제 제출 방식 설정 추가
- 
---
(관련 이미지 첨부)  
---

FEAT: 커리큘럼 편집 내 과제 제출 방식 설정 추가

---

src/App.jsx
src/component/api/api.js
src/component/api/classApi.js
src/component/api/usersApi.js
src/component/page/Class.jsx
src/component/page/ClassList.jsx
src/component/page/Participate.jsx
src/component/page/users/ChangePassword.jsx
src/component/page/users/FindPassword.jsx
src/component/page/users/LogIn.jsx
src/component/page/users/SignUp.jsx
src/component/page/users/UsersInfoContainer.jsx
src/component/ui/TopBar.jsx
src/component/ui/class/AdminTopBar.jsx
src/component/ui/class/ClassTopbar.jsx
src/style/Styles.jsx

---
- closed: #113 
---
- 임시 비밀번호 받는 API 연결
- 비밀번호 변경 API 연결
- 공유 버튼 눌렀을 때 출력
- 관리 페이지에서 새로고침시 강의 목록으로 가는 에러 수정
---
https://github.com/user-attachments/assets/81e1431e-baf1-4634-9f40-4d3b2aa61571
---

feat: 비밀번호 관련 API 연동

---

src/App.jsx
src/component/api/usersApi.js

---
- test-v-0.2.1
---
- 페이지 나가 있으면 새로고침해야지 자동 로그아웃 되는 현상 수정
- 
---
(관련 이미지 첨부)  
---

fkx: 자동 로그아웃 페이지 이동마다 체크

---

src/component/page/users/UsersInfoContainer.jsx
src/component/ui/TopBar.jsx

---
- closed: #138
---
- 일반 로그인시 비밀번호 변경 버튼 비활성화
- 
---
(관련 이미지 첨부)  
---

mod: 일반 로그인시 비밀번호 변경 버튼 비활성화

---

src/component/page/class/Setting.jsx

---
- closed: #138 
---
- 정해지지 않았어요 설정 시 타임 포맷 오류 수정
- 
---
(관련 이미지 첨부)  
---
예빈님 찾아주셔서 감사해요 😲

fix: 정해지지 않았어요 설정 시 타임 포맷 오류 수정

---

src/component/page/class/Curriculum.jsx
src/component/page/class/CurriculumEdit.jsx
src/component/ui/class/EditButton.jsx
src/component/ui/curriculum/DateTimeEdit.jsx

---
- closed: #150 
---
- 커리큘럼 편집 저장 시 기간 설정 검토
- 기간 미설정 시 못 넘어가도록 로직 추가 (+alert)
---
(관련 이미지 첨부)  
---

FEAT: 커리큘럼 편집 저장 시 기간 설정 검토

---

src/component/page/class/AssignmentSubmit.jsx
src/component/page/class/Playing.jsx

---
- closed: #138 
---
- 과제 제출 화면 및 강의 수가 화면 커리큘럼 사이드바 필터링 추가
- 
---
(관련 이미지 첨부)  
---

feat: 커리큘럼 사이드바 필터링 추가

---

package-lock.json
package.json
src/component/page/class/AssignmentSubmit.jsx
src/component/page/class/Overview.jsx
src/component/ui/class/AssignmentSubmitBox.jsx
src/component/ui/class/EditButton.jsx
src/component/ui/class/EditNoticeButton.jsx

---
- closed: #158 
---
- 개요에서는 순수 텍스트 개수만 세어서 500자로 제한
- 과제 제출에서는 5000자로 제한
---
- 디스코드 화면과 동일
---

FIX: 강의 개요와 과제 제출에서 글자 수 제한

---

src/component/api/classApi.js
src/component/page/Class.jsx
src/component/page/class/Admin.jsx
src/component/page/class/admin/Setting.jsx
src/component/ui/class/AdminTopBar.jsx
src/component/ui/class/ClassTopbar.jsx

---
- closed: #162 
---
- 관리 페이지(Admin)에서 API가 중복 호출 되는 것을 수정합니다.
- Class.jsx에서 불러온 내용을 Admin에 전달하고 또 AdimTopBar로 전달하고 자식 컴포넌트들이 사용함
- 
---
(관련 이미지 첨부)  
---

fix: 관리 페이지 API 중복 호출 수정

---

src/component/page/ClassList.jsx
src/component/page/class/Create.jsx
src/component/page/class/Notice.jsx
src/component/page/dashboard/Dashboard.jsx
src/component/page/dashboard/Sidebar.jsx
src/component/page/dashboard/TaskList.jsx
src/component/page/dashboard/WeekCalendar.jsx
src/component/page/users/UsersInfoContainer.jsx
src/component/ui/TopBar.jsx
src/component/ui/class/AdminTopBar.jsx
src/component/ui/class/ClassLayout.jsx

---
- closed: #164 
---
- PageLayout을 공통적으로 사용하여서 여백 통일함
- border-radius도 15px로 전반적으로 통일함
---
https://github.com/user-attachments/assets/85cbd9bb-0966-49f7-8ae2-58c49dff5b6d
---
- Creat.jsx에서 캘린더 아이콘이 계속 재랜더링 되는 것 수정함

DESIGN: 페이지 간 여백 통일

---

src/component/page/ClassList.jsx
src/component/page/Participate.jsx
src/component/ui/TopBar.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

design: 대시보드 버튼 수정, 충돌 수정

---

src/component/ui/DragZone.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

mod: 파일 최대 추가 개수 3 -> 10 변경

---

src/component/api/api.js
src/component/api/usersApi.js
src/component/page/users/GoogleAccountLink.jsx
src/component/page/users/GoogleAuthCallback.jsx

---
- closed: #177 
---
- 토큰 재발급 구현(refreshToken)
- 
---
(관련 이미지 첨부)  
---

FEAT: 토큰 재발급 구현(refreshToken)

---

src/App.jsx
src/component/api/usersApi.js
src/component/page/users/GoogleAccountLink.jsx
src/component/page/users/GoogleAuthCallback.jsx
src/component/ui/ChannelTalk.jsx

---
- closed: #177 
---
- refreshtoken 관련 오류 해결
- 
---
(관련 이미지 첨부)  
---

FIX : refreshtoken 관련 오류 해결

---

src/App.jsx
src/component/api/api.js
src/component/api/tokenManager.js
src/component/api/usersApi.js
src/component/contexts/LanguageContext.jsx
src/component/contexts/usersContext.jsx
src/component/page/users/GoogleAccountLink.jsx
src/component/page/users/GoogleAuthCallback.jsx

---
- closed: #177 
---
- 리프레시 토큰 오류 해결
- 중복 호출 오류 해결
---
(관련 이미지 첨부)  
---

FIX: 리프레시 토큰 오류 및 중복 호출 문제 해결

---

src/component/page/class/Curriculum.jsx
src/component/page/class/CurriculumEdit.jsx
src/component/ui/class/AdminTopBar.jsx
src/component/ui/class/CurriculumSidebar.jsx
src/component/ui/curriculum/CurriculumSection.jsx
src/component/ui/curriculum/DateTimeEdit.jsx
src/component/ui/curriculum/EditableSection.jsx

---
- closed: #174 
---
- 
- 
---
(관련 이미지 첨부)  
데스크탑
500px
모바일
---

design: 커리큘럼 페이지 스타일 변경

---

src/component/page/class/admin/StudentDetail.jsx
src/component/ui/class/ClassLayout.jsx

---
---
- 
- 
---
(관련 이미지 첨부)  
---

FIX: 빌드 제출 전 수정

---

src/component/page/class/Create.jsx
src/component/ui/CustomTimePicker.jsx

---
- closed: #189 
---
- 정해지지 않았어요 클릭 후에 다른 요일 선택시 다른 선택이 풀리고 다른 요일이 클릭 되도록 구현
- 정해지지 않았어요 클릭시에 설정 되었어요! 메세지로 변경되는 것이 아니라, 메세지는 유지하고 색상만 변경
- 정해지지 않았어요 배경/글자 색상과 월화수목금~ 색상 통일
- 시간 설정 후에 시계 버튼이 아닌 배경을 눌러도 저장될 수 있도록
- 화면 사이즈에 맞게 여백 수정
---
(관련 이미지 첨부)  
---

mod: 강의실 생성 페이지 수정사항 반영

---

src/App.jsx
src/component/api/api.js
src/component/api/tokenManager.js
src/component/page/ClassList.jsx
src/component/page/users/LogIn.jsx
src/component/page/users/UsersInfoContainer.jsx
src/component/ui/TopBar.jsx
src/utils/collectVisibleTexts.js

---
- closed: #192 
---
- API 에러가 났을 때 자동 로그아웃 기능 추가
- 번역 기능 실행했을 때 iframe 출력되는 거 수정
- 번역 기능 로그인 여부 상관 없이 출력되도록 위치 수정
- 로그인 페이지 디자인 수정
- 외부 앱에서 웹 접속 후 구글 로그인 막히는 기능 안드로이드는 외부 브라우저로 이동되게 수정 
- 본인 강의실일 경우 강의실 목록에서 휴지통 아이콘 미출력
---
(관련 이미지 첨부)  
---

FIX: 여러 에러 수정
